site_name: ECNet Documentation
nav:
  - Installation: index.md
  - API Documentation:
    - ecnet.model: api_model.md
    - ecnet.datasets: api_datasets.md
    - ecnet.tasks: api_tasks.md
    - ecnet.blends: api_blends.md
    - ecnet.callbacks: api_callbacks.md
theme:
  name: "material"
plugins:
  - search
  - mkdocstrings